[project]
name = "setup-dev-environment"
version = "0.1.0"
description = "mkdocs-material to render *.md files to static web site files"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]
